
package daopersonne;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DAOPersonneWS", targetNamespace = "http://DaoPersonne/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DAOPersonneWS {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "create", targetNamespace = "http://DaoPersonne/", className = "daopersonne.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://DaoPersonne/", className = "daopersonne.CreateResponse")
    @Action(input = "http://DaoPersonne/DAOPersonneWS/createRequest", output = "http://DaoPersonne/DAOPersonneWS/createResponse")
    public void create(
        @WebParam(name = "arg0", targetNamespace = "")
        Personne arg0);

    /**
     * 
     * @return
     *     returns java.util.List<daopersonne.Personne>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectAll", targetNamespace = "http://DaoPersonne/", className = "daopersonne.SelectAll")
    @ResponseWrapper(localName = "selectAllResponse", targetNamespace = "http://DaoPersonne/", className = "daopersonne.SelectAllResponse")
    @Action(input = "http://DaoPersonne/DAOPersonneWS/selectAllRequest", output = "http://DaoPersonne/DAOPersonneWS/selectAllResponse")
    public List<Personne> selectAll();

    /**
     * 
     * @param arg0
     * @return
     *     returns daopersonne.Personne
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findById", targetNamespace = "http://DaoPersonne/", className = "daopersonne.FindById")
    @ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://DaoPersonne/", className = "daopersonne.FindByIdResponse")
    @Action(input = "http://DaoPersonne/DAOPersonneWS/findByIdRequest", output = "http://DaoPersonne/DAOPersonneWS/findByIdResponse")
    public Personne findById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
