
package daopersonne;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServiceDAOPersonneService", targetNamespace = "http://DaoPersonne/", wsdlLocation = "http://192.168.1.34:8586/DAOPersonneWS?WSDL")
public class ServiceDAOPersonneService
    extends Service
{

    private final static URL SERVICEDAOPERSONNESERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICEDAOPERSONNESERVICE_EXCEPTION;
    private final static QName SERVICEDAOPERSONNESERVICE_QNAME = new QName("http://DaoPersonne/", "ServiceDAOPersonneService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.1.34:8586/DAOPersonneWS?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICEDAOPERSONNESERVICE_WSDL_LOCATION = url;
        SERVICEDAOPERSONNESERVICE_EXCEPTION = e;
    }

    public ServiceDAOPersonneService() {
        super(__getWsdlLocation(), SERVICEDAOPERSONNESERVICE_QNAME);
    }

    public ServiceDAOPersonneService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICEDAOPERSONNESERVICE_QNAME, features);
    }

    public ServiceDAOPersonneService(URL wsdlLocation) {
        super(wsdlLocation, SERVICEDAOPERSONNESERVICE_QNAME);
    }

    public ServiceDAOPersonneService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICEDAOPERSONNESERVICE_QNAME, features);
    }

    public ServiceDAOPersonneService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceDAOPersonneService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DAOPersonneWS
     */
    @WebEndpoint(name = "DAOPersonneWSPort")
    public DAOPersonneWS getDAOPersonneWSPort() {
        return super.getPort(new QName("http://DaoPersonne/", "DAOPersonneWSPort"), DAOPersonneWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DAOPersonneWS
     */
    @WebEndpoint(name = "DAOPersonneWSPort")
    public DAOPersonneWS getDAOPersonneWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://DaoPersonne/", "DAOPersonneWSPort"), DAOPersonneWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICEDAOPERSONNESERVICE_EXCEPTION!= null) {
            throw SERVICEDAOPERSONNESERVICE_EXCEPTION;
        }
        return SERVICEDAOPERSONNESERVICE_WSDL_LOCATION;
    }

}
