package fr.atatorus.bookservice.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.12
 * 2020-02-19T12:53:55.818+01:00
 * Generated source version: 3.2.12
 *
 */
@WebServiceClient(name = "CalculService",
                  wsdlLocation = "http://localhost:8080/bookservice/services/calcul?wsdl",
                  targetNamespace = "http://services.bookservice.atatorus.fr/")
public class CalculService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://services.bookservice.atatorus.fr/", "CalculService");
    public final static QName CalculPort = new QName("http://services.bookservice.atatorus.fr/", "CalculPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/bookservice/services/calcul?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CalculService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/bookservice/services/calcul?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CalculService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CalculService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CalculService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CalculService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CalculService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns Calcul
     */
    @WebEndpoint(name = "CalculPort")
    public Calcul getCalculPort() {
        return super.getPort(CalculPort, Calcul.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Calcul
     */
    @WebEndpoint(name = "CalculPort")
    public Calcul getCalculPort(WebServiceFeature... features) {
        return super.getPort(CalculPort, Calcul.class, features);
    }

}
