package fr.atatorus.bookservice.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.12
 * 2020-02-19T12:53:55.790+01:00
 * Generated source version: 3.2.12
 *
 */
@WebService(targetNamespace = "http://services.bookservice.atatorus.fr/", name = "Calcul")
@XmlSeeAlso({ObjectFactory.class})
public interface Calcul {

    @WebMethod
    @RequestWrapper(localName = "mult", targetNamespace = "http://services.bookservice.atatorus.fr/", className = "fr.atatorus.bookservice.services.Mult")
    @ResponseWrapper(localName = "multResponse", targetNamespace = "http://services.bookservice.atatorus.fr/", className = "fr.atatorus.bookservice.services.MultResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String mult(
        @WebParam(name = "nb1", targetNamespace = "")
        int nb1,
        @WebParam(name = "nb2", targetNamespace = "")
        int nb2
    );

    @WebMethod
    @RequestWrapper(localName = "add", targetNamespace = "http://services.bookservice.atatorus.fr/", className = "fr.atatorus.bookservice.services.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://services.bookservice.atatorus.fr/", className = "fr.atatorus.bookservice.services.AddResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String add(
        @WebParam(name = "nb1", targetNamespace = "")
        int nb1,
        @WebParam(name = "nb2", targetNamespace = "")
        int nb2
    );

    @WebMethod
    @RequestWrapper(localName = "div", targetNamespace = "http://services.bookservice.atatorus.fr/", className = "fr.atatorus.bookservice.services.Div")
    @ResponseWrapper(localName = "divResponse", targetNamespace = "http://services.bookservice.atatorus.fr/", className = "fr.atatorus.bookservice.services.DivResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String div(
        @WebParam(name = "nb1", targetNamespace = "")
        int nb1,
        @WebParam(name = "nb2", targetNamespace = "")
        int nb2
    );

    @WebMethod
    @RequestWrapper(localName = "sous", targetNamespace = "http://services.bookservice.atatorus.fr/", className = "fr.atatorus.bookservice.services.Sous")
    @ResponseWrapper(localName = "sousResponse", targetNamespace = "http://services.bookservice.atatorus.fr/", className = "fr.atatorus.bookservice.services.SousResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String sous(
        @WebParam(name = "nb1", targetNamespace = "")
        int nb1,
        @WebParam(name = "nb2", targetNamespace = "")
        int nb2
    );
}
