package projetClientBookService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.12
 * 2020-02-19T11:56:22.852+01:00
 * Generated source version: 3.2.12
 *
 */
@WebService(targetNamespace = "http://services.bookservice.atatorus.fr/", name = "Hello")
@XmlSeeAlso({ObjectFactory.class})
public interface Hello {

    @WebMethod
    @RequestWrapper(localName = "hello", targetNamespace = "http://services.bookservice.atatorus.fr/", className = "fr.atatorus.bookservice.services.Hello_Type")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://services.bookservice.atatorus.fr/", className = "fr.atatorus.bookservice.services.HelloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String hello(
        @WebParam(name = "nom", targetNamespace = "")
        java.lang.String nom
    );
}
