
package projetsoapdaoserver;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DaoPersonneWS", targetNamespace = "http://projetSoapDaoServer/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DaoPersonneWS {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "create", targetNamespace = "http://projetSoapDaoServer/", className = "projetsoapdaoserver.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://projetSoapDaoServer/", className = "projetsoapdaoserver.CreateResponse")
    @Action(input = "http://projetSoapDaoServer/DaoPersonneWS/createRequest", output = "http://projetSoapDaoServer/DaoPersonneWS/createResponse")
    public void create(
        @WebParam(name = "arg0", targetNamespace = "")
        Personne arg0);

    /**
     * 
     * @return
     *     returns java.util.List<projetsoapdaoserver.Personne>
     */
    @WebMethod(operationName = "SelectAll")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SelectAll", targetNamespace = "http://projetSoapDaoServer/", className = "projetsoapdaoserver.SelectAll")
    @ResponseWrapper(localName = "SelectAllResponse", targetNamespace = "http://projetSoapDaoServer/", className = "projetsoapdaoserver.SelectAllResponse")
    @Action(input = "http://projetSoapDaoServer/DaoPersonneWS/SelectAllRequest", output = "http://projetSoapDaoServer/DaoPersonneWS/SelectAllResponse")
    public List<Personne> selectAll();

    /**
     * 
     * @param x
     * @return
     *     returns projetsoapdaoserver.Personne
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findById", targetNamespace = "http://projetSoapDaoServer/", className = "projetsoapdaoserver.FindById")
    @ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://projetSoapDaoServer/", className = "projetsoapdaoserver.FindByIdResponse")
    @Action(input = "http://projetSoapDaoServer/DaoPersonneWS/findByIdRequest", output = "http://projetSoapDaoServer/DaoPersonneWS/findByIdResponse")
    public Personne findById(
        @WebParam(name = "x", targetNamespace = "")
        int x);

}
