
package projetsoapdaoserver;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServiceDaoPersonneService", targetNamespace = "http://projetSoapDaoServer/", wsdlLocation = "http://127.0.0.1:8586/DaoPersonneWS?WSDL")
public class ServiceDaoPersonneService
    extends Service
{

    private final static URL SERVICEDAOPERSONNESERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICEDAOPERSONNESERVICE_EXCEPTION;
    private final static QName SERVICEDAOPERSONNESERVICE_QNAME = new QName("http://projetSoapDaoServer/", "ServiceDaoPersonneService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8586/DaoPersonneWS?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICEDAOPERSONNESERVICE_WSDL_LOCATION = url;
        SERVICEDAOPERSONNESERVICE_EXCEPTION = e;
    }

    public ServiceDaoPersonneService() {
        super(__getWsdlLocation(), SERVICEDAOPERSONNESERVICE_QNAME);
    }

    public ServiceDaoPersonneService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICEDAOPERSONNESERVICE_QNAME, features);
    }

    public ServiceDaoPersonneService(URL wsdlLocation) {
        super(wsdlLocation, SERVICEDAOPERSONNESERVICE_QNAME);
    }

    public ServiceDaoPersonneService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICEDAOPERSONNESERVICE_QNAME, features);
    }

    public ServiceDaoPersonneService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceDaoPersonneService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DaoPersonneWS
     */
    @WebEndpoint(name = "DaoPersonneWSPort")
    public DaoPersonneWS getDaoPersonneWSPort() {
        return super.getPort(new QName("http://projetSoapDaoServer/", "DaoPersonneWSPort"), DaoPersonneWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DaoPersonneWS
     */
    @WebEndpoint(name = "DaoPersonneWSPort")
    public DaoPersonneWS getDaoPersonneWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://projetSoapDaoServer/", "DaoPersonneWSPort"), DaoPersonneWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICEDAOPERSONNESERVICE_EXCEPTION!= null) {
            throw SERVICEDAOPERSONNESERVICE_EXCEPTION;
        }
        return SERVICEDAOPERSONNESERVICE_WSDL_LOCATION;
    }

}
